"""Declarative Rev A circuit, derived from DESIGN_SPECIFICATION.md and user decisions.

This script writes JSON only. KiCad files are generated by KiCad Companion MCP.
"""

import json
from pathlib import Path


parts = []


def add(ref, lib_id, value, footprint, pins, function, mpn=None, dnp=False):
    fields = {"Function": function}
    if mpn:
        fields["MPN"] = mpn
    parts.append(
        {
            "ref": ref,
            "lib_id": lib_id,
            "value": value,
            "footprint": footprint,
            "pins": pins,
            "fields": fields,
            "dnp": dnp,
        }
    )


R0603 = "Resistor_SMD:R_0603_1608Metric"
R1206 = "Resistor_SMD:R_1206_3216Metric"
C0603 = "Capacitor_SMD:C_0603_1608Metric"
C0805 = "Capacitor_SMD:C_0805_2012Metric"


def resistor(ref, value, a, b, function, footprint=R0603):
    add(ref, "Device:R", value, footprint, {"1": a, "2": b}, function)


def capacitor(ref, value, a, b, function, footprint=C0603):
    add(ref, "Device:C", value, footprint, {"1": a, "2": b}, function)


# Power and precision reference.
add("J1", "Connector_Generic:Conn_02x05_Odd_Even", "FPGA_Events_2x5",
    "Connector_PinHeader_2.54mm:PinHeader_2x05_P2.54mm_Vertical",
    {"1": "GND", "2": "3V3", "3": "SPIKE_ON_TL", "4": "SPIKE_OFF_TL",
     "5": "SPIKE_ON_TR", "6": "SPIKE_OFF_TR", "7": "SPIKE_ON_BL",
     "8": "SPIKE_OFF_BL", "9": "SPIKE_ON_BR", "10": "SPIKE_OFF_BR"},
    "FPGA event and power interface")
add("J2", "Connector_Generic:Conn_01x06", "Analog_Debug",
    "Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical",
    {"1": "GND", "2": "VREF", "3": "VPHOTO_TL", "4": "VPHOTO_TR",
     "5": "VPHOTO_BL", "6": "VPHOTO_BR"}, "Analog debug interface")
add("J3", "Connector_Generic:Conn_01x02", "LED_Enable_Input",
    "Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical",
    {"1": "LED_EN", "2": "GND"}, "FPGA-controlled IR emitter enable")
add("FB1", "Device:L_Ferrite", "BLM18AG601SN1D",
    "Inductor_SMD:L_0603_1608Metric", {"1": "3V3", "2": "3V3_ANALOG"},
    "Analog supply filter", "BLM18AG601SN1D")
add("U17", "Reference_Voltage:REF3012", "REF3312AIDBZR",
    "Package_TO_SOT_SMD:SOT-23-3",
    {"1": "3V3_ANALOG", "2": "VREF", "3": "GND"},
    "1.25 V reference; REF3012 symbol is pin compatible", "REF3312AIDBZR")
capacitor("C25", "1uF", "VREF", "GND", "Reference bypass")
capacitor("C26", "100nF", "VREF", "GND", "Reference high-frequency bypass")
capacitor("C27", "10uF", "3V3_ANALOG", "GND", "Analog bulk bypass", C0805)
capacitor("C28", "10uF", "3V3", "GND", "Digital bulk bypass", C0805)
capacitor("C29", "10uF", "3V3", "GND", "IR emitter bulk bypass", C0805)

# Thresholds: 1.2902 V and 1.2098 V for ideal 3.3 V/1.25 V rails.
resistor("R28", "499k", "3V3_ANALOG", "VTH_ON", "ON threshold upper leg")
resistor("R29", "10.0k", "VTH_ON", "VREF", "ON threshold lower leg")
resistor("R30", "10.0k", "VREF", "VTH_OFF", "OFF threshold upper leg")
resistor("R31", "301k", "VTH_OFF", "GND", "OFF threshold lower leg")
for part in parts:
    if part["ref"] in {"R28", "R29", "R30", "R31"}:
        part["fields"]["Tolerance"] = "0.1%"

# Low-side LED drive. J3 makes LED_EN externally accessible and R27 holds it off.
resistor("R25", "82R", "3V3", "LED_A", "IR emitter current limit", R1206)
add("D5", "Device:LED", "TSAL6200", "LED_THT:LED_D5.0mm",
    {"1": "LED_K", "2": "LED_A"}, "940 nm emitter", "TSAL6200")
add("Q1", "Transistor_FET:AO3400A", "AO3400A",
    "Package_TO_SOT_SMD:SOT-23",
    {"1": "LED_GATE", "2": "GND", "3": "LED_K"},
    "Low-side IR emitter switch", "AO3400A")
resistor("R26", "100R", "LED_EN", "LED_GATE", "MOSFET gate series resistor")
resistor("R27", "100k", "LED_GATE", "GND", "MOSFET gate pull-down")


for channel_index, quadrant in enumerate(("TL", "TR", "BL", "BR"), start=1):
    summing = f"TIA_IN_{quadrant}"
    photo = f"VPHOTO_{quadrant}"
    event = f"VEVENT_{quadrant}"
    # Cathode at VREF summing node, anode at GND: 1.25 V reverse bias.
    # Photocurrent leaves the summing node and raises VPHOTO through RF.
    add(f"D{channel_index}", "VBPW34S:VBPW34S", "VBPW34S",
        "VBPW34S:XDCR_VBPW34S", {"K": summing, "A": "GND"},
        f"{quadrant} photodiode; supplied Vishay pad geometry verified", "VBPW34S")
    add(f"U{channel_index}", "Amplifier_Operational:OPA197xDGK",
        "OPA381AIDGKR", "Package_SO:MSOP-8_3x3mm_P0.65mm",
        {"1": None, "2": summing, "3": "VREF", "4": "GND", "5": None,
         "6": photo, "7": "3V3_ANALOG", "8": None},
        f"{quadrant} TIA; OPA197 symbol is pin compatible", "OPA381AIDGKR")
    resistor(f"R{channel_index}", "18.0k", summing, photo,
             f"{quadrant} transimpedance feedback")
    capacitor(f"C{channel_index}", "47pF", summing, photo,
              f"{quadrant} feedback, C0G")
    capacitor(f"C{8 + channel_index}", "100nF", "3V3_ANALOG", "GND",
              f"{quadrant} TIA local bypass")
    capacitor(f"C{4 + channel_index}", "100nF", photo, event,
              f"{quadrant} temporal coupling")
    resistor(f"R{4 + channel_index}", "22k", event, "VREF",
             f"{quadrant} adaptation return")
    add(f"U{4 + channel_index}", "Comparator:MCP6562", "TLV3202AIDR",
        "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm",
        {"1": f"RAW_ON_{quadrant}", "2": "VTH_ON", "3": event,
         "4": "GND", "5": f"VTH_OFF_{quadrant}", "6": event,
         "7": f"RAW_OFF_{quadrant}", "8": "3V3_ANALOG"},
        f"{quadrant} ON/OFF comparators; MCP6562 symbol is pin compatible",
        "TLV3202AIDR")
    capacitor(f"C{12 + channel_index}", "100nF", "3V3_ANALOG", "GND",
              f"{quadrant} comparator local bypass")
    # Optional positive feedback. Each OFF threshold has a local 10k feed,
    # preventing one channel's hysteresis from coupling into the other three.
    resistor(f"R{39 + channel_index}", "10.0k", "VTH_OFF",
             f"VTH_OFF_{quadrant}", f"{quadrant} OFF threshold local feed")
    add(f"R{30 + 2 * channel_index}", "Device:R", "2.0M", R0603,
        {"1": f"RAW_ON_{quadrant}", "2": event},
        f"{quadrant} optional ON hysteresis", dnp=True)
    add(f"R{31 + 2 * channel_index}", "Device:R", "2.0M", R0603,
        {"1": f"RAW_OFF_{quadrant}", "2": f"VTH_OFF_{quadrant}"},
        f"{quadrant} optional OFF hysteresis", dnp=True)
    for polarity_index, polarity in enumerate(("ON", "OFF")):
        event_index = (channel_index - 1) * 2 + polarity_index + 1
        raw = f"RAW_{polarity}_{quadrant}"
        rext = f"REXT_{polarity}_{quadrant}"
        cext = f"CEXT_{polarity}_{quadrant}"
        qout = f"OS_OUT_{polarity}_{quadrant}"
        spike = f"SPIKE_{polarity}_{quadrant}"
        add(f"U{8 + event_index}", "74xGxx:74LVC1G123", "SN74LVC1G123DCU",
            "Package_SO:VSSOP-8_2.3x2mm_P0.5mm",
            {"1": "GND", "2": raw, "3": "3V3", "4": "GND",
             "5": qout, "6": cext, "7": rext, "8": "3V3"},
            f"{quadrant} {polarity} one-shot", "SN74LVC1G123DCU")
        capacitor(f"C{29 + event_index}", "100nF", "3V3", "GND",
                  f"{quadrant} {polarity} one-shot local bypass")
        resistor(f"R{8 + event_index}", "8.2k", "3V3", rext,
                 f"{quadrant} {polarity} pulse width")
        capacitor(f"C{16 + event_index}", "12nF", cext, rext,
                  f"{quadrant} {polarity} pulse width")
        resistor(f"R{16 + event_index}", "150R", qout, spike,
                 f"{quadrant} {polarity} event output series")


# Required analog threshold and raw-event probe points.
probe_nets = ["VTH_ON", "VTH_OFF"] + [
    f"RAW_{polarity}_{quadrant}"
    for quadrant in ("TL", "TR", "BL", "BR")
    for polarity in ("ON", "OFF")
]
for index, net in enumerate(probe_nets, start=1):
    add(f"TP{index}", "Connector:TestPoint", net,
        "TestPoint:TestPoint_Pad_D1.0mm", {"1": net}, f"Probe {net}")

# Four M3 board mounts and two M2 lens-holder mounts. The user confirmed
# the 20 mm lens-holder hole spacing fits their part.
for index in range(1, 7):
    footprint = (
        "MountingHole:MountingHole_3.2mm_M3"
        if index <= 4 else "MountingHole:MountingHole_2.2mm_M2"
    )
    add(f"H{index}", "Mechanical:MountingHole", "MountingHole",
        footprint, {}, "Board mount" if index <= 4 else "Lens holder mount")


spec = {
    "title": "Neuromorphic IR Event Sensor",
    "revision": "Rev A candidate",
    "notes": "Design specification plus user decisions: 10-pin event header, VBPW34S, FPGA-controlled LED_EN. Nominal VTH_ON 1.2903 V and VTH_OFF 1.2098 V at 3.300/1.250 V; R28-R31 0.1%. This candidate is not yet fabrication approved.",
    "power_flags": "auto",
    "parts": parts,
}
output = Path(__file__).with_name("spec.json")
output.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {output} with {len(parts)} parts")
