M48
; DRILL file KiCad 10.0.6 date 2026-09-26T17:14:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T17:14:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X15.0Y-18.0
X35.0Y-18.0
T2
X3.5Y-3.5
X3.5Y-66.5
X46.5Y-3.5
X46.5Y-66.5
M30
